Uk/jira/LOK-2830: When update Citus adminUser, lokahi services not works properly.
OpenNMS-Cloud/lokahi-helm-charts pull request #18
Opened 2024-09-27 11:47 UTC by Umairk95

2024-09-30 17:14 UTC, MuhammadTalhaDataQHealth approved these changes

2024-09-30 17:22 UTC, tahir-abb approved these changes

2024-10-01 13:28 UTC, mershad-manesh commented on dependencies/citus/templates/citus-worker-statefulset.yaml
> +            - '{{ .Values.global.citus.databaseName | default .Values.databaseName }}'
This be `{{ .Values.global.citus.adminUser | default .Values.Citus.adminUser }}`

the value passed to `-U` is the username

2024-10-01 13:29 UTC, mershad-manesh requested changes
few minor tweaks are required

2024-10-01 16:14 UTC, Umairk95 commented on dependencies/citus/templates/citus-worker-statefulset.yaml
> +            - '{{ .Values.global.citus.databaseName | default .Values.databaseName }}'
yes right,  Username and database both added.

2024-10-01 16:14 UTC, Umairk95 commented on dependencies/citus/templates/citus-worker-statefulset.yaml
> +            - '{{ .Values.global.citus.databaseName | default .Values.databaseName }}'
yes right,  Username and database both added

2024-10-01 17:50 UTC, mershad-manesh commented
In Lokahi `values.yaml` file we have
```
global:
 ...
  citus:            # Override citus default port, database name, adminUser and adminPassword in lokahi globally
    port: ~
    adminUser: ~
    adminPassword: ~
    databaseName: ~
...
# Enables integration of Citus with notification module.
Citus:
  enabled: true
  adminUser: desenv
  adminPassword: notset
  port: 5432
```

What happens if I set  different values for these properties? Which one has the higher priority ?

2024-10-02 08:57 UTC, Umairk95 commented
> In Lokahi `values.yaml` file we have
> 
> ```
> global:
>  ...
>   citus:            # Override citus default port, database name, adminUser and adminPassword in lokahi globally
>     port: ~
>     adminUser: ~
>     adminPassword: ~
>     databaseName: ~
> ...
> # Enables integration of Citus with notification module.
> Citus:
>   enabled: true
>   adminUser: desenv
>   adminPassword: notset
>   port: 5432
> ```
> 
> What happens if I set different values for these properties? Which one has the higher priority ?

2024-10-02 09:00 UTC, Umairk95 commented
> In Lokahi `values.yaml` file we have
> 
> ```
> global:
>  ...
>   citus:            # Override citus default port, database name, adminUser and adminPassword in lokahi globally
>     port: ~
>     adminUser: ~
>     adminPassword: ~
>     databaseName: ~
> ...
> # Enables integration of Citus with notification module.
> Citus:
>   enabled: true
>   adminUser: desenv
>   adminPassword: notset
>   port: 5432
> ```
> 
> The values in global have higher priority, if any value in global is set to  NIL then it will take default value from Citus values.

2024-10-07 17:19 UTC, mershad-manesh approved these changes
Took a quick look at the changes, they look good

2024-10-08 09:06 UTC, merged