LOK-2342 Document the properties in values files
OpenNMS-Cloud/lokahi-helm-charts pull request #5
Opened 2024-03-20 18:03 UTC by Umairk95

2024-03-20 18:50 UTC, mershad-manesh commented on dependencies/citus/values.yaml
> +  workersEnabled: true
I think we can remove the extra space at the end of this line

2024-03-20 18:52 UTC, mershad-manesh commented on dependencies/cortex/values.yaml
> +  port: 9000 # ConfigMap http port
I feel like we can expand on what we mean by `ConfigMap http port`. 
Maybe we can just say what this port number is used for.

2024-03-20 18:54 UTC, mershad-manesh commented on dependencies/mail-server/values.yaml
> +  smtpPort: 1025 #smtp port
I think we can remove this comment

2024-03-20 18:55 UTC, mershad-manesh commented on lokahi-minion/values.yaml
> +  grpcClientKeystorePassword: ""  # GRPC_CLIENT_KEYSTORE_PASSWORD
We should expand on what `GRPC_CLIENT_KEYSTORE_PASSWORD` is

2024-03-20 18:57 UTC, mershad-manesh requested changes
Overall it looks good. A couple of items needs to be tweaked

2024-03-21 14:26 UTC, Umairk95 commented on dependencies/citus/values.yaml
> +  workersEnabled: true
made changes

2024-03-21 14:28 UTC, Umairk95 commented on lokahi-minion/values.yaml
> +  grpcClientKeystorePassword: ""  # GRPC_CLIENT_KEYSTORE_PASSWORD
changes done

2024-03-21 16:30 UTC, MuhammadTalhaDataQHealth approved these changes

2024-03-21 16:32 UTC, merged